ARCHIVO_PEDIDOS = "./carpeta_archivos/pedidos.json"
ARCHIVO_TECNICOS = "./carpeta_archivos/tecnicos.json"
ARCHIVO_STOCK = "./carpeta_archivos/stock.json"
PRIORIDADES = ("Baja", "Media", "Alta", "Urgente")
TIPOSDETRABAJOS = ("Aire acondicionado", "Electricidad", "Soporte tecnico")
CATEGORIAS_STOCK = ("Aire acondicionado", "Electricidad", "Soporte tecnico", "General")
ESTADOS = ("Pendiente", "asignado", "En proceso", "Terminado", "Cancelado")
REGEXTELEFONO = r"([0-9]{2,4})(15)([0-9]{6,8})"
REGEXID = r"([0-9]+)"
REGEXTECNICOS = r"([A-Za-z]*)"
REGEXPRECIO = r"([0-9]+(\.[0-9]+)?)"
